accounts/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, PasswordField, SubmitField, validators
from wtforms.validators import DataRequired, EqualTo, Length, AnyOf, Regexp


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    firstname = StringField('First Name', validators=[DataRequired()])
    lastname = StringField('Last Name', validators=[DataRequired()])
    phone = StringField('Phone number', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(),
                                                     Length(min=8, max=15, message='Password must be between 8 and 15 characters!'),
                                                     Regexp("(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*\W)", message="Password must contain at least 1 uppercase letter, 1 lowercase letter, 1 digit and 1 special character!")])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message='Both password fields must be equal!')])
    submit = SubmitField('Register')

class LoginForm(FlaskForm):
    email = StringField('email', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    otp = StringField('MFA code')
    recaptcha = RecaptchaField("verify you are a human")
    submit = SubmitField('Log In')

posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField(validators=[DataRequired()])
    body = TextAreaField(validators=[DataRequired()])
    submit = SubmitField()

accounts/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, session, get_flashed_messages
from flask_login import login_user, logout_user, current_user
from flask_sqlalchemy.session import Session
from flask_wtf import FlaskForm
from sqlalchemy import false
from markupsafe import Markup
import pyotp
from wtforms.validators import NoneOf

from accounts.forms import RegistrationForm, LoginForm
from config import User, db, limiter

accounts_bp = Blueprint('accounts', __name__, template_folder='templates')
max_login_attempts = 3



@accounts_bp.route('/registration', methods=['GET','POST'])
def registration():
    form = RegistrationForm()

    if form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).first():
            flash('Email already exists', category="danger")
            return render_template('accounts/registration.html', form=form)

        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        )

        db.session.add(new_user)
        db.session.commit()

        flash('Account Created. You have to enable Multi-Factor Authentication first to login', category='success')
        return render_template('accounts/mfasetup.html', secret=new_user.mfakey, uri=new_user.uri())

    return render_template('accounts/registration.html', form=form)

@accounts_bp.route('/login', methods=['GET','POST'])
@limiter.limit("20 per minute")
def login():
    form = LoginForm()

    if not "login_attempts" in session:
        session["login_attempts"] = 0

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if user.verify_password(form.password.data):
                session["login_attempts"] = 0
                if user.verify_otp(form.otp.data):
                    if not user.mfaenabled:
                        user.mfaenabled = True
                        db.session.commit()
                    login_user(user)
                    flash('Login Successful', category='success')
                    return redirect(url_for('posts.posts'))
                if not user.mfaenabled:
                    flash('MFA is not enabled. You have to enable Multi-Factor Authentication first to login', category='danger')
                    return render_template('accounts/mfasetup.html', secret=user.mfakey, uri=user.uri())


        session['login_attempts'] += 1

        if session['login_attempts'] >= max_login_attempts:
            flash(Markup('You have tried to log in too many times. Please click <a href="\\unlock">here</a> to unlock account.'), category='danger')
            return render_template('accounts/login.html')

        flash('Invalid Credentials. You have ' + str(max_login_attempts - session.get('login_attempts')) + ' attempt(s) remaining.', category="danger")
        return redirect(url_for('accounts.login'))

    return render_template('accounts/login.html', form=form)


@accounts_bp.route('/account')
def account():
    return render_template('accounts/account.html', user=current_user)

@accounts_bp.route('/unlock')
def unlock():
    session["login_attempts"] = 0
    return redirect(url_for('accounts.login'))

@accounts_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

app.py
from flask import render_template
from config import app

@app.route('/')
def index():
    return render_template('home/index.html')

@app.errorhandler(429)
def ratelimit(e):
    return render_template("errors/error.html"), 429


if __name__ == '__main__':
    app.run()

posts/views.py
from flask import Blueprint, render_template, flash, url_for, redirect
from flask_login import current_user

from config import db, Post
from posts.forms import PostForm
from sqlalchemy import desc

posts_bp = Blueprint('posts', __name__, template_folder='templates')


@posts_bp.route('/posts')
def posts():
    all_posts = Post.query.order_by(desc('id')).all()
    return render_template('posts/posts.html', posts=all_posts)


@posts_bp.route('/create', methods=('GET', 'POST'))
def create():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post(userid=current_user.id, title=form.title.data, body=form.body.data)

        db.session.add(new_post)
        db.session.commit()

        flash('Post created', category='success')
        return redirect(url_for('posts.posts'))

    return render_template('posts/create.html', form=form)


@posts_bp.route('/<int:id>/update', methods=('GET', 'POST'))
def update(id):
    post_to_update = Post.query.filter_by(id=id).first()

    if not post_to_update:
        return redirect(url_for('posts.posts'))

    form = PostForm()

    if form.validate_on_submit():
        post_to_update.update(userid=current_user.id, title=form.title.data, body=form.body.data)

        flash('Post updated', category='success')
        return redirect(url_for('posts.posts'))

    form.title.data = post_to_update.title
    form.body.data = post_to_update.body

    return render_template('posts/update.html', form=form)

@posts_bp.route('/<int:id>/delete')
def delete(id):
    Post.query.filter_by(id=id).delete()
    db.session.commit()

    flash('Post deleted', category='success')
    return redirect(url_for('posts.posts'))

security/views.py
from flask import Blueprint, render_template

security_bp = Blueprint('security', __name__, template_folder='templates')

@security_bp.route('/security')
def security():
    return render_template('security/security.html')

templates/accounts/account.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Account</h1>
        <div class="p-2 row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="p-2 bg-light border border-primary" style="text-align: left">

                    <h5><b>Account No:</b> {{ user.id }}</h5>
                    <h5><b>Email:</b> {{ user.email }}</h5>
                    <h5><b>First Name:</b> {{ user.firstname }}</h5>
                    <h5><b>Last Name:</b> {{ user.lastname }}</h5>
                    <h5><b>Phone No:</b> {{ user.phone }}</h5>
                    <h5><b>Posts:</b></h5>

                    {% for post in user.posts %}
                    <div class="card border border-dark">

                        <div class="card-header bg-dark text-white border border-dark">
                            <h4>{{ post.title }}</h4>
                            <h6>Author: {{ post.user.firstname }} {{ post.user.lastname }}</h6>
                            <small>{{ post.created.strftime('%H:%M:%S %d-%m-%Y') }}</small>
                        </div>
                        <div class="card-body">{{ post.body }}</div>

                        <div class="card-footer">
                            <a class="navbar-item" href="{{ url_for('posts.update', id=post.id) }}">Update</a>
                            <a class="navbar-item" href="{{ url_for('posts.delete', id=post.id) }}">Delete</a>
                        </div>

                    </div>
                    <br>
                    {% endfor %}

                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

	<div class="container">
        <h1>Login</h1>
        <div class="p-2 row">
            <div class="col-3"></div>
            <div class="col-6">
                <div>
                    <p>Please complete the following form to log into your account to use the CSC2031 Blog.</p>
                </div>

                {% if form %}
                    <form method="POST">
                        <div class="p-2 bg-light border border-primary">
                            <div style="text-align: left">
                                {{ form.csrf_token() }}
                                <div>
                                    {% with messages = get_flashed_messages(with_categories=true) %}
                                    {% for category, message in messages %}
                                    <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                        {{ message }}. Go to <a href="{{ url_for('accounts.registration') }}">registration page</a>.
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                                            <span>&times;</span>
                                        </button>
                                    </div>
                                    {% endfor %}
                                    {% endwith %}
                                </div>
                                <div class="form-group">
                                    {{ form.email.label }}<span style="color: red">*</span>
                                    {{ form.email(class="form-control") }}
                                    {{ form.password.label }}<span style="color: red">*</span>
                                    {{ form.password(class="form-control") }}
                                    {{ form.otp.label }}<span style="color: red">*</span>
                                    {{ form.otp(class="form-control") }}
                                    {{ form.recaptcha.label }}<span style="color: red">*</span>
                                    {{ form.recaptcha(class="form-control") }}
                                </div>
                            </div>
                            <div>
                                {{ form.submit(class="btn btn-success") }}
                            </div>
                        </div>
                    </form>
                {% else %}
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% for category, message in messages %}
                        <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                                <span>&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                        {% endwith %}
                {% endif %}

            </div>
            <div class="col-3"></div>
        </div>

    </div>

{% endblock %}

templates/accounts/mfasetup.html
{% extends "base.html" %}

{% block content %}

	<div class="container">
        <h1>Multi-Factor Authentication Setup</h1>
        <div class="p-2 row">
            <div class="col-1"></div>
                <div class="col-10">
                    <div>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% for category, message in messages %}
                            <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                                    <span>&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        {% endwith %}
                    </div>
                    <div style="font-family: sans-serif; font-size: larger">
                        <div class="p-2 bg-light border">
                            Open an authenticator app (e.g. Microsoft Authenticator, Google Authenticator, Authy) on your mobile.
                        </div>
                        <div class="p-2 bg-light border">
                            Select add new account.
                        </div>
                        <div class="p-2 bg-light border">
                            Manually enter Code or scan QR code below.
                        </div>
                        <div class="p-2 bg-light border border-primary" style="margin: 2%;">
                            <h2><b>Code</b></h2>
                            <p style="font-size: xx-large">{{ secret }}</p>
                            <h2><b>QR</b></h2>
                            <img src={{ qrcode(uri, box_size=5, border=5) }}>
                        </>
                    </div>
                    <div>
                        Once you have entered the code or scanned the QR, please click <a href="{{ url_for('accounts.login') }}">here</a>.
                    </div>
                </div>
            <div class="col-1"></div>
        </div>
    </div>

{% endblock %}

templates/accounts/registration.html
{% extends "base.html" %}

{% block content %}
    <style>
        ul.no-bullets {
          list-style-type: none;
          margin: 0;
          padding: 0;
        }
    </style>

    <div class="container">
        <h1>Registration</h1>
        <div class="p-2 row">
            <div class="col-3"></div>
            <div class="col-6">
                <div>
                    <p>Please complete the following form to register an account to use the CSC2031 Blog.</p>
                </div>

                <form method="POST">
                    <div class="p-2 bg-light border border-primary">
                        <div style="text-align: left">
                            {{ form.csrf_token() }}
                            <div>
                                {% with messages = get_flashed_messages(with_categories=true) %}
                                {% for category, message in messages %}
                                <div class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                    {{ message }}. Go to <a href="{{ url_for('accounts.login') }}">login page</a>.
                                    <button type="button" class="btn-close" data-bs-dismiss="alert"
                                            onclick=delete_flash(this)>
                                        <span>&times;</span>
                                    </button>
                                </div>
                                {% endfor %}
                                {% endwith %}
                            </div>

                            <div class="form-group">
                                <div>
                                    {{ form.email.label}}<span style="color: red">*</span>
                                    {{ form.email(class="form-control") }}
                                </div>
                                <div>
                                    {{ form.firstname.label}}<span style="color: red">*</span>
                                    {{ form.firstname(class="form-control") }}
                                </div>
                                <div>
                                    {{ form.lastname.label}}<span style="color: red">*</span>
                                    {{ form.lastname(class="form-control") }}
                                </div>
                                <div>
                                    {{ form.phone.label}}<span style="color: red">*</span>
                                    {{ form.phone(class="form-control") }}
                                </div>
                                <div>
                                    {{ form.password.label}}<span style="color: red">*</span>
                                    {{ form.password(class="form-control") }}
                                    {% for error in form.password.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div>
                                    {{ form.confirm_password.label}}<span style="color: red">*</span>
                                    {{ form.confirm_password(class="form-control") }}
                                    {% for error in form.confirm_password.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div>
                            {{ form.submit(class="btn btn-success") }}
                        </div>
                    </div>
                </form>

            </div>
            <div class="col-3"></div>
        </div>

    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>CSC2031</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    </head>
    <body>
        <style>
            .table {
                margin-left: auto;
                margin-right: auto;
            }
        </style>

        <section class="container-fluid p-3 my-3">

            <nav class="nav nav-pills flex-column flex-sm-row">

                <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('accounts.registration') }}">Registration</a>
                <a class="nav-item nav-link" href="{{ url_for('accounts.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('accounts.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('posts.posts') }}">Posts</a>
                <a class="nav-item nav-link" href="{{ url_for('posts.create') }}">Create</a>
                <a class="nav-item nav-link" href="{{ url_for('security.security') }}">Security</a>
                <a class="nav-item nav-link" href="http://127.0.0.1:5000/admin">DB Admin</a>
                <a class="nav-item nav-link" href="{{ url_for('accounts.logout') }}">Logout</a>

            </nav>

            <div class="container-fluid p-3 my-5 text-center">

            {% block content %}
                <!-- The content of any template extending the base template will be embedded in this block -->
            {% endblock %}

            </div>
        </section>
    </body>
</html>

templates/home/index.html
{% extends "base.html" %}

{% block content %}
    <h1>CSC2031 Blog</h1>
    <p>Benjamin Wray 230215371</p>
{% endblock %}

templates/posts/create.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Create Post</h1>
        <div class="p-2 row">
            <div class="col-2"></div>
            <div class="col-8">
                <form method="POST">
                    <div class="p-2 bg-light border border-primary" style="text-align: left">

                        {{ form.csrf_token() }}
                        <div class="form-group">
                            {{ form.title.label}}<span style="color: red">*</span>
                            {{ form.title(class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form.body.label}}<span style="color: red">*</span>
                            {{ form.body(class="form-control", rows='10') }}
                        </div>
                        <div>
                            {{ form.submit(class="btn btn-success") }}
                        </div>
                    </div>
                </form>
            </div>
        <div class="col-2"></div>
    </div>
</div>
{% endblock %}

templates/posts/posts.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Posts</h1>
        <div class="p-2 row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="p-2 bg-light border border-primary" style="text-align: left">

                    <div>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% for category, message in messages %}
                                <div style="text-align: left" class="alert alert-{{ category }} mt-3 alert-dismissible" role="alert">
                                    {{ message }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" onclick=delete_flash(this)>
                                        <span>&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endwith %}
                    </div>

                    {% for post in posts %}
                    <div class="card border border-dark">

                        <div class="card-header bg-dark text-white border border-dark">
                            <h4>{{ post.title }}</h4>
                            <h6>Author: {{ post.user.firstname }} {{ post.user.lastname }}</h6>
                            <small>{{ post.created.strftime('%H:%M:%S %d-%m-%Y') }}</small>
                        </div>
                        <div class="card-body">{{ post.body }}</div>

                        <div class="card-footer">
                            <a class="navbar-item" href="{{ url_for('posts.update', id=post.id) }}">Update</a>
                            <a class="navbar-item" href="{{ url_for('posts.delete', id=post.id) }}">Delete</a>
                        </div>

                    </div>
                    <br>
                    {% endfor %}

                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
{% endblock %}

templates/posts/update.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Update Post</h1>
        <div class="p-2 row">
            <div class="col-2"></div>
            <div class="col-8">
                <form method="POST">
                    <div class="p-2 bg-light border border-primary" style="text-align: left">
                        {{ form.csrf_token() }}
                        <div class="form-group">
                            {{ form.title.label}}<span style="color: red">*</span>
                            {{ form.title(class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form.body.label}}<span style="color: red">*</span>
                            {{ form.body(class="form-control", rows='10') }}
                        </div>
                        <div>
                            {{ form.submit(class="btn btn-success") }}
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
{% endblock %}

templates/security/security.html
{% extends "base.html" %}

{% block content %}
    <h1>Security</h1>
{% endblock %}